twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: ['bundles/TwigBundle/Form/bootstrap_5_layout.html.twig']
  globals:
    app_datetime_format: "eee, d MMMM y', godz.' H:mm" # https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax
    app_datetime_short_format: "ee.MM.y', godz.' H:mm" # https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax
    app_name: '%env(APP_NAME)%'
    app_meta_title: '%env(APP_META_TITLE)%'
    app_meta_description: '%env(APP_META_DESCRIPTION)%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
  twig:
    strict_variables: true
