# Dashboard
panel_dashboard:
  path: /panel
  controller: App\Controller\Panel\DashboardController::index

panel_dashboard_publish_daily_image:
  path: /panel/publish-daily-image/{imageId}
  controller: App\Controller\Panel\DashboardController::publishDailyImage

panel_dashboard_remove_daily_image:
  path: /panel/remove-daily-image/{imageId}
  controller: App\Controller\Panel\DashboardController::removeDailyImage

panel_dashboard_publish_daily_video:
  path: /panel/publish-daily-video/{videoId}
  controller: App\Controller\Panel\DashboardController::publishDailyVideo

panel_dashboard_remove_daily_video:
  path: /panel/remove-daily-video/{videoId}
  controller: App\Controller\Panel\DashboardController::removeDailyVideo

panel_dashboard_publish_user_gas_station_price:
  path: /panel/publish-user-gas-price/{gasStationPriceId}
  controller: App\Controller\Panel\DashboardController::publishUserGasStationPrice

panel_dashboard_remove_user_gas_station_price:
  path: /panel/remove-user-gas-price/{gasStationPriceId}
  controller: App\Controller\Panel\DashboardController::removeUserGasStationPrice

panel_dashboard_publish_advertisement:
  path: /panel/publish-advertisement/{advertisementId}
  controller: App\Controller\Panel\DashboardController::publishAdvertisement

panel_dashboard_save_next_sunday_is_shopping:
  path: /panel/save-next-sunday-is-shopping
  methods: [ POST ]
  controller: App\Controller\Panel\DashboardController::saveNextSundayIsShopping

panel_dashboard_save_pharmacy_duty:
  path: /panel/save-pharmacy-duty
  methods: [ POST ]
  controller: App\Controller\Panel\DashboardController::savePharmacyDuty

panel_dashboard_publish_company:
  path: /panel/publish-company/{companyId}
  controller: App\Controller\Panel\DashboardController::publishCompany

panel_dashboard_remove_company:
  path: /panel/remove-company/{companyId}
  controller: App\Controller\Panel\DashboardController::removeCompany

# Advertisements
panel_advertisement_list:
  path: /panel/advertisements
  controller: App\Controller\Panel\AdvertisementController::list

panel_advertisement_remove:
  path: /panel/advertisement/{advertisementId}/remove
  controller: App\Controller\Panel\AdvertisementController::remove

panel_advertisement_toggle_promoted:
  path: /panel/advertisements/{advertisementId}/toggle-promoted
  controller: App\Controller\Panel\AdvertisementController::togglePromoted

panel_advertisement_toggle_active:
  path: /panel/advertisements/{advertisementId}/toggle-active
  controller: App\Controller\Panel\AdvertisementController::toggleActive

panel_advertisement_edit:
  path: /panel/advertisements/{advertisementId}/edit
  controller: App\Controller\Panel\AdvertisementController::edit

# Promo items
panel_ad_list:
  path: /panel/ads
  controller: App\Controller\Panel\PromoItemController::list

panel_ad_create:
  path: /panel/ads/create
  controller: App\Controller\Panel\PromoItemController::create

panel_ad_edit:
  path: /panel/ads/{id}/edit
  controller: App\Controller\Panel\PromoItemController::edit

panel_ad_delete:
  path: /panel/ads/{id}/delete
  controller: App\Controller\Panel\PromoItemController::delete

# Auth
panel_login:
  path: /panel/login
  controller: App\Controller\Panel\SecurityController::login

panel_logout:
  path: /panel/logout
  controller: App\Controller\Panel\SecurityController::logout

# Articles
panel_article_change_status:
  path: /panel/articles/{id}/change-status/{status}
  controller: App\Controller\Panel\ArticleController::changeStatus

panel_article_bump:
  path: /panel/articles/{id}/bump
  controller: App\Controller\Panel\ArticleController::bump

panel_article_delete:
  path: /panel/articles/{id}/delete
  controller: App\Controller\Panel\ArticleController::delete

panel_article_edit:
  path: /panel/articles/{id}/edit
  controller: App\Controller\Panel\ArticleController::edit

panel_article_list:
  path: /panel/articles
  controller: App\Controller\Panel\ArticleController::list

panel_article_create:
  path: /panel/articles/create
  controller: App\Controller\Panel\ArticleController::create

panel_article_comment_hide:
  path: /panel/articles/comments/{commentId}/hide
  controller: App\Controller\Panel\ArticleCommentController::hideComment

panel_article_comment_unlock:
  path: /panel/articles/comments/{commentId}/unlock
  controller: App\Controller\Panel\ArticleCommentController::unlockComment

# Categories
panel_categories_change_order:
  path: /panel/categories/change-order
  controller: App\Controller\Panel\CategoryController::changeOrder

panel_categories_create:
  path: /panel/categories/create
  controller: App\Controller\Panel\CategoryController::create

panel_categories_edit:
  path: /panel/categories/{id}/edit
  controller: App\Controller\Panel\CategoryController::edit

panel_categories_list:
  path: /panel/categories
  controller: App\Controller\Panel\CategoryController::list

panel_categories_delete:
  path: /panel/categories/{id}/delete
  controller: App\Controller\Panel\CategoryController::delete

panel_categories_move_articles:
  path: /panel/categories/move-articles/{fromCategoryId}/{toCategoryId}
  controller: App\Controller\Panel\CategoryController::moveArticles

# Galleries
panel_gallery_create:
  path: /panel/galleries/create
  controller: App\Controller\Panel\GalleryController::create

panel_gallery_delete:
  path: /panel/galleries/{id}/delete
  controller: App\Controller\Panel\GalleryController::delete

panel_gallery_edit:
  path: /panel/galleries/{id}/edit
  controller: App\Controller\Panel\GalleryController::edit

panel_gallery_list:
  path: /panel/galleries
  controller: App\Controller\Panel\GalleryController::list

# User management
panel_user_create:
  path: /panel/users/create
  controller: App\Controller\Panel\UserController::create

panel_user_delete:
  path: /panel/users/{id}/delete
  controller: App\Controller\Panel\UserController::delete

panel_user_edit:
    path: /panel/users/{id}/edit
    controller: App\Controller\Panel\UserController::edit

panel_user_list:
  path: /panel/users
  controller: App\Controller\Panel\UserController::list

# User report
panel_user_report_hide:
  path: /panel/user-report/{reportId}/hide
  controller: App\Controller\Panel\UserReportController::hideReport

panel_user_report_unlock:
  path: /panel/user-report/{reportId}/unlock
  controller: App\Controller\Panel\UserReportController::unlockReport

# Gas prices
panel_gas_station:
  path: /panel/gas-station
  controller: App\Controller\Panel\GasPriceController::stationList

panel_gas_station_change_order:
  path: /panel/gas-station/change-order
  controller: App\Controller\Panel\GasPriceController::changeStationOrder

panel_gas_station_create:
  path: /panel/gas-station/create
  controller: App\Controller\Panel\GasPriceController::createStation

panel_gas_station_delete:
  path: /panel/gas-station/{id}/delete
  controller: App\Controller\Panel\GasPriceController::deleteStation

panel_gas_station_edit:
  path: /panel/gas-station/{id}/edit
  controller: App\Controller\Panel\GasPriceController::editStation

panel_gas_station_set_prices:
  path: /panel/gas-station/set-prices
  controller: App\Controller\Panel\GasPriceController::setPrices

# Static pages
panel_static_page_list:
  path: /panel/static-pages
  controller: App\Controller\Panel\StaticPageController::list

panel_static_page_create:
  path: /panel/static-pages/create
  controller: App\Controller\Panel\StaticPageController::create

panel_static_page_edit:
  path: /panel/static-pages/{id}/edit
  controller: App\Controller\Panel\StaticPageController::edit

panel_static_page_delete:
  path: /panel/static-pages/{id}/delete
  controller: App\Controller\Panel\StaticPageController::delete

# Temp
# TODO: move to controllers with low priority for application_category
panel_temporary_development_status:
  path: /panel/development-status
  controller: App\Controller\Panel\DevelopmentStatusController::index

# Company Catalog
panel_company_list:
  path: /panel/companies
  controller: App\Controller\Panel\CompanyController::list

panel_company_create:
  path: /panel/companies/create
  controller: App\Controller\Panel\CompanyController::create

panel_company_edit:
  path: /panel/companies/{id}/edit
  controller: App\Controller\Panel\CompanyController::edit

panel_company_delete:
  path: /panel/companies/{id}/delete
  controller: App\Controller\Panel\CompanyController::delete

# Company Categories
panel_company_category_list:
  path: /panel/company-categories
  controller: App\Controller\Panel\CompanyCategoryController::list

panel_company_category_create:
  path: /panel/company-categories/create
  controller: App\Controller\Panel\CompanyCategoryController::create

panel_company_category_edit:
  path: /panel/company-categories/{id}/edit
  controller: App\Controller\Panel\CompanyCategoryController::edit

panel_company_category_delete:
  path: /panel/company-categories/{id}/delete
  controller: App\Controller\Panel\CompanyCategoryController::delete
