homepage:
  path: /
  controller: App\Controller\HomeController::index

# User report
user_report:
  path: /raport
  controller: App\Controller\UserReportController::index

user_report_add:
  path: /raport/dodaj
  controller: App\Controller\UserReportController::add

# Article category
article_category_old_redirect:
  path: /dzial-{__category}
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: article_category
    permanent: true

# Article details
article_details_old_redirect:
  path: /info/{slug}.{id}.html
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    _locale: pl
    __category: info
    route: article_details
    permanent: true

article_details:
  path: /{__category}/{id}/{slug}
  controller: App\Controller\ArticleController::details

article_events_list_date:
  path: /kalendarz-wydarzen/{date}
  controller: App\Controller\ArticleController::eventsListDate

article_events_list:
  path: /kalendarz-wydarzen
  controller: App\Controller\ArticleController::eventsList

# Promo item redirect
promo_item_redirect:
  path: /promo/redirect/{id}/{redirectUrl}
  controller: App\Controller\PromoItemController::targetUrlRedirect
  requirements:
    id: \d+
    redirectUrl: .*

# User content
user_content_add_image_form:
  path: /przeslij/zdjecie
  controller: App\Controller\UserContentController::addImage

user_content_add_video_form:
  path: /przeslij/film
  controller: App\Controller\UserContentController::addVideo

user_content_add_gas_station_prices_form:
  path: /przeslij/ceny-paliw
  controller: App\Controller\UserContentController::addGasStationPrices

user_content_thank_you:
  path: /przeslij/dziekujemy
  controller: App\Controller\UserContentController::thankYouPage

# At the end of the file
article_category:
  path: /{__category}
  controller: App\Controller\ArticleController::list
