<?php

declare(strict_types=1);

namespace App\DataFixtures;

use App\Entity\Advertisement;
use App\Entity\AdvertisementCategory;
use App\Entity\NameDay;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Faker\Factory;
use Monolog\DateTimeImmutable;
use Symfony\Component\String\Slugger\AsciiSlugger;

class NameDayFixtures extends Fixture
{
    private const DAY_NAMES = [
        1 => [
            1 => 'Mieczysław, Mieszko, Maria, Mieczysława, Masław, Odys, Odyseusz, Wilhelm, Piotr',
            2 => 'Abel, Bazyli, Narcyz, Aspazja, Grzegorz, Makary, Odylon, Telesfor, Jakubina, Telesfora, Achacy, Achacjusz',
            3 => 'Arleta, Anter, Daniel, Danuta, Enoch, Meliton, Teonas, Genowefa, Teona, Piotr',
            4 => 'Aniela, Angelika, Benedykta, Dobromir, Eugeniusz, Krystiana, Grzegorz, Fereol, Tytus, Rygobert, Suligost',
            5 => 'Amata, Emiliana, Edward, Szymon, Piotr',
            6 => 'Andrzej, Jędrzej, Baltazar, Epifania, Kacper, Kasper, Melchior, Norman, Miłowit, Miłwit, Wiltruda',
            7 => 'Chociesław, Julian, Lucjan, Kryspin, Rajmund, Walenty, Rajnold',
            8 => 'Mścisław, Seweryn, Teofil, Mroczysław',
            9 => 'Adrian, Antoni, Julian, Marcelin, Marcjanna, Przemir, Piotr',
            10 => 'Agaton, Danuta, Dobrosław, Jan, Kolumba, Nikanor, Paweł, Wilhelm, Anna, Leonia, Piotr, Petroniusz',
            11 => 'Feliks, Hilary, Honorata, Hortensja, Hortensjusz, Hygin, Matylda, Odon, Krzesimir',
            12 => 'Antoni, Arkadiusz, Wiktorian, Bonet, Arkady, Benedykt, Bonitus, Czesława, Bonita, Ernest, Tacjan, Tacjana, Wiktoriana, Wiktorianna, Tygriusz, Piotr, Marcin',
            13 => 'Bogumił, Bogusław, Gotfryd, Leoncjusz, Melania, Weronika',
            14 => 'Feliks, Hilary, Amadea, Krystiana, Nina, Otto, Rajner, Saba, Mściwuj, Piotr, Krzesimir',
            15 => 'Aleksander, Dąbrówka, Dobrawa, Domosław, Makary, Maur, Paweł, Ida, Micheasz, Piotr, Habakuk, Tarsycja',
            16 => 'Marceli, Waldemar, Waleriusz, Treweriusz, Włodzimierz, Piotr',
            17 => 'Antoni, Jan, Alba, Sulpicjusz, Rościsław, Przemił',
            18 => 'Beatrycze, Bogumił, Krystyna, Liberata, Lubart, Małgorzata, Zuzanna, Wenerand',
            19 => 'Andrzej, Bernard, Erwin, Erwina, Eufemia, Henryk, Kanut, Mariusz, Marta, Matylda, Sara, Wulstan, Adalryk, Alderyk, Pia',
            20 => 'Dobiegniew, Fabian, Dobrożyźń, Sebastian',
            21 => 'Agnieszka, Patrokles, Epifani, Jarosław, Jarosława, Krystiana, Józefa, Awit, Awita',
            22 => 'Uriel, Anastazy, Dorian, Gaudencjusz, Gaudenty, Dobromysł, Wincenty, Jutrogost',
            23 => 'Emerencja, Ildefons, Jan, Klemens, Maria, Rajmund, Rajmunda',
            24 => 'Chwalibog, Franciszek, Milena, Wera, Ksenia, Rafał, Tymoteusz',
            25 => 'Miłosz, Paweł, Artemia, Albert, Miłobor',
            26 => 'Paula, Skarbimir, Leon, Tymoteusz, Tytus, Leona, Wanda, Żeligniew, Ksenofont, Małostryj',
            27 => 'Aniela, Rozalia, Jan Chryzostom, Jerzy, Julian, Przybysław, Adalruna, Alruna, Angelika, Teodoryk',
            28 => 'Augustyn, Manfred, Manfreda, Flawian, Ildefons, Julian, Karol, Piotr, Roger, Tomasz, Waleriusz, Walery',
            29 => 'Sulpicjusz, Ismena, Gildas, Waleriusz, Zdzisław',
            30 => 'Adelajda, Cyntia, Dobiegniew, Feliks, Gerard, Gerarda, Hiacynta, Maciej, Marcin, Martyna, Sebastian, Teofil, Adalgunda, Adelgunda, Piotr',
            31 => 'Cyrus, Euzebiusz, Jan, Ksawery, Ludwik, Marceli, Marcelin, Marcelina, Eudoksja',
        ],
        2 => [
            1 => 'Brygida, Winand, Winanda, Seweryn, Żegota, Zybert, Zybracht, Zybart, Zygbert, Piotr',
            2 => 'Berwin, Ermentruda, Jagoda, Joanna, Katarzyna, Kornel, Korneli, Korneliusz, Maria, Marian, Marcin, Miłosław, Miłosława, Piotr, Teodoryk',
            3 => 'Błażej, Oskar, Ignacy',
            4 => 'Joanna, Weronika, Częstogoj, Izydor',
            5 => 'Sabbas, Agata, Lubodrog, Awit, Awita, Adelajda, Albwin, Dobiemir, Elpin, Indracht, Jakub, Modest, Przybygniew, Strzeżysława, Rodomił',
            6 => 'Dorota, Leon, Paweł, Leona, Amanda, Zdziewit',
            7 => 'Ryszard, Romuald, Teodor, Partenia, Parteniusz, Rozalia, Romeusz',
            8 => 'Elfryda, Hieronim, Ampeliusz, Gabriela, Gniewomir, Izajasz, Piotr, Polikarp, Juwencja, Juwencjusz, Sebastian, Zyta',
            9 => 'Apolonia, Cyryl, Marian, Pola, Sulisława',
            10 => 'Jacek, Elwira, Scholastyka, Trojan',
            11 => 'Dezydery, Lucjan, Olgierd, Cedmon, Sekundyn, Bertrada, Maria',
            12 => 'Modest, Eulalia, Damian, Ampeliusz, Melecjusz, Norma, Ewa, Radosław',
            13 => 'Arleta, Grzegorz, Katarzyna, Jordana, Toligniew',
            14 => 'Cyryl, Dobiesława, Metody, Auksencja, Auksencjusz, Auksenty, Adolf, Walenty, Piotr, Liliana, Eleukadiusz',
            15 => 'Julia, Jowita, Faustyn, Zygfryda, Jordana, Zygfryd, Klaudia, Klaudiusz, Georgina',
            16 => 'Danuta, Eliasz, Julianna, Izajasz, Daniel, Irena, Samuel, Teodul',
            17 => 'Łukasz, Aleksy, Donat, Zbigniew, Sylwin, Sylwina, Julian',
            18 => 'Konstancja, Szymon, Konstantyna, Klaudiusz, Gertruda, Agapit, Agapita',
            19 => 'Arnold, Konrad, Barbacy, Barbat',
            20 => 'Leon, Ludomira, Leona, Aulus',
            21 => 'Eleonora, Piotr, Gumbert, Pepin',
            22 => 'Małgorzata, Marwald, Konkordia, Wrocisław, Marold, Chociebąd, Arystion',
            23 => 'Marta, Damian, Romana, Izabela, Polikarp, Montan',
            24 => 'Józefa, Bogurad, Sergiusz, Maciej, Marek, Jan, Wieledrog, Ermegarda, Irmegarda, Montan, Eunika',
            25 => 'Cezary, Wiktor, Lubart, Antonina, Adam',
            26 => 'Aleksander, Dionizy, Mirosław, Klaudian, Gerlinda',
            27 => 'Gabriel, Anastazja, Auksencja, Baldomer, Auksencjusz, Auksenty, Baldomera, Honoryna, Bazyli, Anna',
            28 => 'Ludomir, Roman, Falibog, Gaja, Makary, Oswald, Kaja, August (w latach nieprzestępnych), Gajusz',
            29 => 'Ariusz, Roman, Dobrosiodł, August, Lutosław, Teofil' // Tylko w latach przestępnych
        ],
        3 => [
            1 => 'Feliks, Herakles, Józef, Eudokia, Leon, Nicefor, Leona, Antoni, Joanna, Radosław, Budzisław, Albin',
            2 => 'Absalon, Paweł, Januaria, Agnieszka, Symplicjusz, Michał, Helena, Franciszek, Henryk, Krzysztof, Prosper',
            3 => 'Wirzchosława, Gerwina, Asteriusz, Samuel, Gerwin, Kinga, Kamila, Maryn, Maryniusz, Kunegunda, Tycjan, Piotr',
            4 => 'Adrian, Leonard, Lucjusz, Gerarda, Eugeniusz, Kazimierz, Gerard, Arkadiusz, Jakubina, Piotr',
            5 => 'Adrian, Fryderyk, Pakosław, Jan, Oliwia, Marek, Euzebiusz',
            6 => 'Eugenia, Róża, Jordana, Koleta, Frydolin, Wiktor, Jordan, Będzimysł',
            7 => 'Paweł, Bazyli, Tomasz, Nadmir, Felicyta, German, Eubul',
            8 => 'Miłogost, Wincenty, Stefan, Filemon, Jan, Julian, Beata, Herenia',
            9 => 'Mścisława, Dominik, Tarazjusz, Prudencjusz, Franciszka, Katarzyna, Przemyślibor',
            10 => 'Makary, Porfirion, Marceli, Cyprian, Aleksander, Zwnisława, Gajus, Gaja, Piotr',
            11 => 'Benedykt, Konstantyn, Prokop, Sofroniusz, Trofim, Kandyd, Drogosława, Konstanty',
            12 => 'Bernard, Józefina, Grzegorz, Blizbor, Piotr',
            13 => 'Roderyk, Patrycja, Bożena, Marek, Kasjan, Ernest, Trzebiesław, Krystyna, Letycja',
            14 => 'Fawila, Michał, Afrodyzy, Pamela, Bożeciecha, Matylda, Leona, Afrodyzjusz, Afrodyzja, Leon, Jakub, Piotr, Ewa',
            15 => 'Klemens, Ludwika, Longina, Longin, Gościmir, Krzysztof, Placyd',
            16 => 'Hilary, Abraham, Cyriak, Hiacynt, Izabela, Artemia, Natalis, Herbert, Miłostryj',
            17 => 'Agrykola, Ambroży, Cieszysław, Gertruda, Józef, Patrycjusz, Patrycy, Patryk, Paweł, Regina, Witburga, Zbigniew, Zbygniew, Zbygniewa',
            18 => 'Aleksa, Narcyz, Boguchwał, Anzelm, Cyryl, Marta, Edward, Salwator, Aleksander, Trofim, Celestyna',
            19 => 'Bogdan, Jan, Józef, Leoncjusz, Marceli, Marek, Sybillina',
            20 => 'Klemens, Klaudia, Bogusław, Ambroży, Eufemia, Cyriaka, Wincenty, Patrycjusz, Anatol, Aleksander, Fotyna, Józefa, Ermegarda, Irmegarda, Kutbert, Wolfram, Archip',
            21 => 'Benedykt, Marzanna, Klemencja, Mikołaj, Filemon, Ludomira, Teodul',
            22 => 'Paweł, Bogusław, August, Kazimierz, Katarzyna, Godzisław, Baldwin, Baldwina, Bazyli, Lea',
            23 => 'Feliks, Pelagia, Zbysław, Eberhard, Wiktoriana, Wiktorianna, Wiktorian, Konrad, Piotra, Pelagiusz, Katarzyna, Oktawian',
            24 => 'Sewer, Sofroniusz, Marek, Aldmir, Oldmir, Szymon, Dzirżysława, Gabriel, Bertrada, Ademar',
            25 => 'Mariola, Dyzma, Nikodem, Maria, Lutomysł, Ireneusz, Dula',
            26 => 'Feliks, Emanuel, Emanuela, Teodor, Larysa, Nicefor, Manuela, Tworzymir, Bazyli, Montan',
            27 => 'Benedykt, Ernest, Lidia, Jan',
            28 => 'Aleksander, Doroteusz, Guntram, Renata, Ingbert, Joanna, Kastor, Malachiasz, Malkolm, Pryskus, Rogat, Stefan',
            29 => 'Wiktoryn, Marek, Eustazy, Czcirad, Cyryl',
            30 => 'Amelia, Leonard, Dobromir, Amadea, Kwiryna, Kwiryn, Mamertyn, Aniela, Litobor, Częstobor, Jan, Mamertyna, Piotr',
            31 => 'Gwido, Beniamin, Kornelia, Dobromira, Balbina, Amos, Achacjusz, Achacy',
        ],
        4 => [
            1 => 'Hugo, Zbigniew, Grażyna, Meliton, Teodora, Katarzyna, Tolisław, Jakubina',
            2 => 'Laurencja, Franciszek, Urban, Miłobąd',
            3 => 'Sykstus, Ryszard, Antoni, Pankracy, Cieszygor, Jakub',
            4 => 'Benedykt, Ambroży, Zdzimir, Izydor, Teodul',
            5 => 'Irena, Wincenty, Borzywoj, Tristan',
            6 => 'Zachariasz, Wilhelm, Diogenes, Zachary, Katarzyna, Ireneusz, Piotra, Platonida, Celestyna',
            7 => 'Donat, Herman, Przecław, Epifaniusz, Hegezyp, Niestanka',
            8 => 'Sieciesława, Cezaryna, Radosław, August, Apolinary, Cezary, January, Herodion',
            9 => 'Marceli, Maja, Dobrosława, Wadim, Heliodor',
            10 => 'Grodzisław, Makary, Pompejusz, Marek, Apoloniusz, Daniel, Michał, Antoni, Ezechiel, Małgorzata, Henryk',
            11 => 'Filip, Herman, Leon, Jaromir, Gemma, Leona, Hildebrand, Hildebranda, Adolf',
            12 => 'Zenon, Sabbas, Andrzej, Wiktor, Juliusz',
            13 => 'Justyn, Marcjusz, Marcin, Hermenegilda, Przemysł, Przemysław, Małgorzata, Jan, Ida',
            14 => 'Walerian, Tyburcja, Tyburcy, Maria, Tyburcjusz, Julianna, Myślimir, Trofim, Ardalion, Krzysztof, Piotr, Lawiniusz',
            15 => 'Wiktoryn, Olimpia, Modest, Abel, Wszegniew, Anastazja, Tytus, Potencjana, Potencjanna, Sylwester, Sylwestra, Piotr',
            16 => 'Benedykt, Bernadeta, Charyzjusz, Leonid, Erwin, Patrycy, Lambert, Urban, Julia',
            17 => 'Klara, Józef, Robert, Radociech, Anicet, Izydor, Izydora, Aniceta, Jakub, Innocenty',
            18 => 'Gościsław, Bogusław, Apoloniusz, Flawiusz, Bogusława, Alicja, Gosława, Barbara',
            19 => 'Konrada, Leontyna, Werner, Leona, Włodzimierz, Irydion, Cieszyrad, Leon, Pafnucy',
            20 => 'Amalia, Sekundyn, Teodor, Marcelin, Berenika, Agnieszka, Nawoj, Szymon, Sulpicjusz, Czesław, Ursycyn',
            21 => 'Feliks, Addar, Anzelm, Drogomił, Apollo, Apollina, Bartosz, Konrad, Roman',
            22 => 'Łukasz, Wanesa, Gajusz, Teodor, Gaja, Soter, Leonid, Strzeżymir, Leon, Leona, Wirginiusz, Aital, Agapit, Agapita',
            23 => 'Adalbert, Wojciech, Gerard, Helena, Jerzy, Gabriela, Gerarda, Lena',
            24 => 'Fidelis, Erwin, Horacy, Egbert, Grzegorz, Horacjusz, Aleksja, Aleksy, Aleksander, Sabbas',
            25 => 'Kaliksta, Ewodia, Markusław, Jarosław, Ewodiusz, Marek, Piotr',
            26 => 'Marcelin, Klarencjusz, Spycimir, Klet, Marzena, Artemon',
            27 => 'Felicja, Anastazy, Marcin, Zyta, Piotr, Teofil, Andrzej, Kanizjusz, Bożebor',
            28 => 'Paweł, Maria, Waleria, Marek, Przybycześć, Afrodyzy, Afrodyzjusz, Afrodyzja, Arystarch, Andrea, Witalis, Piotr',
            29 => 'Hugo, Bogusław, Robert, Piotr, Ermentruda, Paulin, Ryta, Augustyn, Roberta, Angelina, Wiktor, Katarzyna',
            30 => 'Eutropiusz, Bartłomiej, Chwalisława, Lilla, Katarzyna, Afrodyzy, Afrodyzjusz, Afrodyzja, Jakub, Marian, Andrea, Piotr',
        ],
        5 => [
            1 => 'Jeremiasz, Berta, Briok, Jeremi, Józef, Aniela, Floryna, Lubomir, Jakub, Tamara, Maja',
            2 => 'Zoe, Borys, Zygmunta, Walter, Gwalbert, Walbert, Waldebert, Witomir, Atanazy, Walenty, Zygmunt, Anatol',
            3 => 'Juwenalis, Maria, Alodia, Antonina, Aleksander, Leonia, Tymoteusz, Piotr, Teodul',
            4 => 'Florian, Michał, Paulin, Monika, Grzegorz, January, Antonina, Gotard',
            5 => 'Pius, Teodor, Irena, Zdziebor, Penelopa, Waldemar, Sabrina',
            6 => 'Judyta, Ewodia, Teodor, Gościwit, Benedykta, Ewodiusz, Jurand, Jan, Jakub, Edbert, Miłodrog, Małgorzata, Domagniew, Placyd',
            7 => 'Benedykt, Florian, Gizela, August, Ludomiła, Domicela, Domicjan, Domicjana, Flawia, Róża, Sykstus, Piotr',
            8 => 'Heladiusz, Dezyderia, Amat, Michał, Stanisław, Ida, Achacjusz, Achacy',
            9 => 'Karolina, Hiob, Grzegorz, Mikołaj, Beat',
            10 => 'Gordian, Chociesław, Gordiana, Szymon, Chocsław, Antonin, Częstomir, Samuel, Wiktoryna, Jan, Sylwester, Sylwestra',
            11 => 'Benedykt, Filip, Mamerta, Adalbert, Leon, Gwalbert, Walbert, Waldebert, Stella, Franciszek, Mamert, Lutogniew, Ignacy, Zuzanna, Tadea, Tadeusz',
            12 => 'Wszemił, Dominik, Epifani, Nawoja, Domicjan, Domicjana, Joanna, Pankracy, Jazon, Jan, Domicela, Flawia, Janina, German',
            13 => 'Robert, Gerard, Serwacy, Aaron, Magdalena, Andrzej, Natalis, Gloria, Ciechosław, Gerarda, Dobiesława, Agnieszka, Gemma',
            14 => 'Jeremiasz, Koryna, Bonifacy, Maciej, Wiktor, Dobiesław, Ampeliusz, Fenenna, Izydor',
            15 => 'Strzeżysław, Robert, Cecyliusz, Atanazy, Zofia, Dionizja, Czcibora, Nadzieja, Izydor, Jan, Kasjusz, Florencjusz, Florenty, Piotr',
            16 => 'Germeriusz, Trzebiemysł, Fidol, Wiktoriana, Wiktorianna, Jan Nepomucen, Ubald, Wiktorian, Andrzej, Szymon, Honorat, Jędrzej, Jan, Rambert, Adam',
            17 => 'Weronika, Paschalis, Herakliusz, Sławomir, Bruno, Wiktor, Montan',
            18 => 'Feliks, Wenancjusz, Myślibor, Eryk, Liberiusz, Klaudia, Aleksander, Aleksandra, Teodot',
            19 => 'Celestyn, Potencjana, Potencjanna, Kryspin, Bernarda, Piotr, Iwo, Pękosław, Mikołaj, Augustyn, Pudencjana',
            20 => 'Teodor, Anastazy, Aleksander, Wiktoria, Asteriusz, Bernardyn, Saturnina, Iwo, Bronimir, Rymwid, Józefa',
            21 => 'Tymoteusz, Ryksa, Walenty, Wiktor, Przedsława, Jan, Pudens, Krzysztof, Piotr, Teobald',
            22 => 'Wisława, Emil, Helena, Ryta, Julia, Jan, Krzesisława, Wiesław, Wiesława',
            23 => 'Dezydery, Iwona, Symeon, Michał, Emilia, Dezyderiusz, Budziwoj, Eufrozyna, Jan',
            24 => 'Maria, Wincenty, Milena, Joanna, Zuzanna, Natan, Tomira, Orion, Jan, Cieszysława',
            25 => 'Magdalena, Beda, Leon, Imisława, Grzegorz, Urban, Leona, Wenerand',
            26 => 'Angelika, Filip, Adalwina, Alwina, Adalwin, Alwin, Emil, Ewelina, Paulina, Więcemił, Ariusz',
            27 => 'Lucjan, Magdalena, Oliwer, Radowit, Juliusz, Jan',
            28 => 'Heladiusz, Wilhelm, Emil, Priam, Wiktor, Ignacy, German, Augustyn, Jaromir',
            29 => 'Maksymina, Teodor, Bogusława, Maksymin, Ermentruda, Urszula, Rajmunda, Magdalena, Piotr',
            30 => 'Feliks, Ferdynand, Jan, Andronik, Sulimir, Suligniewa, Bazyli',
            31 => 'Feliks, Teodor, Petronela, Petronia, Kancjusz, Kancjan, Kancjanela, Noe, Kamila'
        ],
        6 => [
            1 => 'Bernard, Nikodem, Alfons, Symeon, Fortunat, Magdalena, Konrad, Felin, Felina, Ischyrion, Juwencja, Juwencjusz, Justyn, Teobald, Pamela, Hannibal',
            2 => 'Blandyna, Marzanna, Marcelin, Efrem, Maria, Trofima, Erazm, Racisław, Nicefor, Piotr, Eugeniusz, Florianna, Floriana, Mikołaj, Marianna, Fotyn, Materna, Domna',
            3 => 'Tamara, Konstantyn, Owidiusz, Leszek, Paula, Cecyliusz, Ferdynand, Klotylda, Owidia, Kewin, Klotylda',
            4 => 'Dacjan, Karol, Braturad, Niepełka, Karp, Franciszek, Saturnina, Gostmił, Aleksander, Skarbisław',
            5 => 'Walter, Waleria, Dobrociech, Bonifacy, Nikanor, Igor, Hildebrand, Hildebranda',
            6 => 'Norberta, Dominika, Benignus, Gerarda, Symeon, Więcerad, Laurenty, Gerard, Klaudiusz, Norbert, Paulina, Kandyda',
            7 => 'Lukrecja, Paweł, Anna, Robert, Jarosław, Antoni, Hadriana, Wisław, Ciechomir, Wiesława, Piotr',
            8 => 'Wyszesław, Wilhelm, Medard, Maksymin, Seweryn, Herakliusz, Medarda, Maksymina, Dobrociech, Jadwiga',
            9 => 'Anna, Felicjan, Pelagia, Sylwester, Sylwestra',
            10 => 'Bogumiła, Mauryn, Bogumił, Apollo, Edgar, Wiktorian, Wiktoriana, Wiktorianna, Ingolf, Małgorzata',
            11 => 'Feliks, Teodozja, Anastazy, Radomił, Barnaba, Witomysł',
            12 => 'Wyszemir, Onufry, Władysława, Jarogniewa, Narcyz, Antonina, Leon, Jan, Jarogniew, Leona, Celestyna, Władysław, Tadea, Placyd, Piotr, Ewa',
            13 => 'Herman, Armand, Chociemir, Lucjan, Gerard, Antoni, Tobiasz, Gerarda, Lubowid, Rambert',
            14 => 'Walerian, Justyn, Eliza, Ninogniew',
            15 => 'Bernard, Abraham, Edburga, Witold, Witosław, Jolanta, Wit, Leonida, Lotar, Angelina, Wisława, Oliwia, Dula',
            16 => 'Benon, Cyryk, Ludgarda, Aneta, Budzimir, Justyna, Jan, Aureusz, Benona, Aubert, Alina, Alena',
            17 => 'Izaura, Laura, Drogomysł, Radomił, Hipacy, Franciszek, Adrianna, Gundolf, Marcjan, Rajner, Adolf, Waleriana, Awit, Awita, Piotr, Montan, Daria',
            18 => 'Elżbieta, Paula, Marek, Efrem, Emil, Gerwazy, Drohobysz, Amanda, Miłobor',
            19 => 'Michalina, Borzysław, Gerwazy, Odo, Protazy, Julianna, Eurydyka, Grymilda',
            20 => 'Bożena, Bogna, Rafał, Edburga, Gemma, Florentyna, Franciszek, Hektor, Michał',
            21 => 'Teodor, Domamir, Demetria, Lutfryd, Alojza, Alojzy, Marcja, Rudolf, Rudolfina, Alicja, Rudolfa, Chloe',
            22 => 'Agenor, Flawiusz, Achacy, Innocenta, Paulina, Achacjusz, Innocenty, Tomasz, Alban',
            23 => 'Józef, Wanda, Agrypina, Zenon, Albin, Anna, Edeltruda',
            24 => 'Emilia, Wilhelm, Danuta, Jan, Janina',
            25 => 'Prosper, Fiebrosław, Wilhelm, Antyd, Eulogiusz, Tolisława, Febronia, Febron, Dorota',
            26 => 'Jeremiasz, Edburga, Paweł, Zdziwoj, Jan, Dawid, Maksencjusz, Maksanty',
            27 => 'Włodzisław, Cyryl, Bożydar',
            28 => 'Paweł, Ekhard, Józef, Zbrosław, Leon, Serena, Leona, Ireneusz, Plutarch, Ekard, Jakert, Heron',
            29 => 'Piotr, Paweł, Dawid, Dalebor, Benedykta, Kasjusz',
            30 => 'Marcjalis, Bazyli, Władysława, Ciechosława, Leon, Emilia, Leona, Lucyna, Trofim, Władysław, Ermentruda, Teobald'
        ],
        7 => [
            1 => 'Bogusław, Halina, Estera, Namir, Karolina, Marcin, Teodoryk, Domicjan, Domicjana, Klarysa, Ekhard, Marian, Jakert',
            2 => 'Otto, Urban, Martynian, Bożydar, Juda, Niegosława, Switun, Juwenalis, Bernardyn',
            3 => 'Heliodor, Jacek, Miłosław, Otto, Oton, Teodot, Tomasz, Leon, Anatol, Leona',
            4 => 'Elżbieta, Aurelian, Aggeusz, Alfred, Teodor, Józef, Odon, Odo, Malwina, Wielisław, Innocenty, Julian, Berta, Ozeasz, Piotr',
            5 => 'Zoe, Marta, Wilhelm, Trofima, Antoni, Przybywoj, Bartłomiej, Jakub, Filomena',
            6 => 'Niegosław, Dominika, Nazaria, Dominik, Ignacja, Gotard, Agrypina, Chociebor, Zuzanna',
            7 => 'Benedykt, Pompejusz, Sędzisława, German, Antoni, Cyryl, Wilibald, Metody',
            8 => 'Adrian, Kilian, Kiliana, Prokop, Eugeniusz, Odeta, Edgar, Chwalimir, Adolf, Adolfa, Piotr, Teobald',
            9 => 'Lukrecja, Zenona, Sylwia, Anatola, Adolfina, Anatolia, Weronika, Ludwika, Patrycjusz, Róża, Zenon, Florianna, Floriana, Hieronim, Mikołaj, Lucja, Teodoryk, Antoni, Kornel, Korneli, Korneliusz, Barbara',
            10 => 'Filip, Aniela, Samson, Zacheusz, Witołd, Amalberga, Sylwan, Witalis, January, Aleksander, Rufina, Rzędziwoj, Engelbert, Askaniusz',
            11 => 'Benedykt, Pius, Pelagia, Siepraw, Olga, Wyszesława, Kalina, Placyd, Sawin, Cyrus, Zybert, Zybracht, Zybart, Zygbert',
            12 => 'Feliks, Paweł, Leon, Epifania, Jan Gwalbert, Leona, Weronika, Euzebiusz, Andrzej, Henryk, Natan, Himisław',
            13 => 'Radomiła, Henryk, Joel, Ernest, Eugeniusz, Małgorzata, Trofima, Sara, Jakub, Ezdrasz',
            14 => 'Marcelin, Ulryk, Kamil, Tuskana, Franciszek, Dobrogost, Kosma, Marceli, Izabela, Damian, Angelina, Wincenty',
            15 => 'Lubomysł, Daniel, Włodzimierz, Roksana, Egon, Ignacy, Niecisław, Dawid, Anna',
            16 => 'Benedykt, Faust, Stefan, Eustacjusz, Eustachy, Andrzej, Dzierżysław, Carmen, Ermegarda, Irmegarda, Maria',
            17 => 'Januaria, Donata, Marcelina, Dzierżykraj, Konstancja, Aneta, Marceli, Andrzej, Aleksja, Karolina, Leon, Aleksy, Leona, Jadwiga, Bogdan, Tarsycja',
            18 => 'Robert, Erwin, Uniesław, Matern, Arnold, Wespazjan, Teodozja, Szymon, Arnolf, Arnulf, Emilian',
            19 => 'Arseniusz, Marcin, Wincenty, Lutobor, Rufin, Zdziesuł, Piotr',
            20 => 'Paweł, Eliasz, Sewera, Hieronim, Małgorzata, Leon, Heliasz, Czesław, Leona, Stosław',
            21 => 'Benedykt, Prokop, Daniel, Ignacy, Andrzej, Wiktor, Julia, Prakseda, Klaudiusz, Arbogast',
            22 => 'Wawrzyniec, Bolesława, Magdalena, Pankracy, Laurencjusz, Albin, Naczęsława, Benona, Stojsław',
            23 => 'Bogna, Apolinary, Apolinaria',
            24 => 'Olga, Antoni, Kinga, Wojciecha, Kunegunda, Krystyna, Zyglinda, Krzesimir',
            25 => 'Walentyna, Nieznamir, Alfons, Olimpia, Rudolf, Rudolfina, Jakub, Sławosław, Krzysztof, Rudolfa, Dariusz',
            26 => 'Anna, Mirosława, Grażyna, Krystiana, Bartłomieja, Hanna, Sancja, Joachim',
            27 => 'Aureli, Pantaleon, Antuza, Natalia, Bertold, Laurenty, Wszebor, Julia, Lilla, Stoisław',
            28 => 'Alfonsa, Samson, Pantaleon, Marcela, Wiktor, Innocenty, Tymona, Tymon, Achacjusz, Achacy',
            29 => 'Konstantyn, Lucyliusz, Olaf, Maria, Faustyn, Serafina, Marta, Urban, Beatrycze, Lucyla, Cierpisław, Prosper',
            30 => 'Ubysław, Ubysława, Ludomiła, Julita, Maryna, Abdon, Julia, Piotr',
            31 => 'Alfonsa, Justyn, German, Helena, Demokryt, Ignacy, Ernesta, Emilian, Beat, Ludomir, Adam, Lubomir'
        ],
        8 => [
            1 => 'Alfons, Justyn, Nadzieja, Piotr, Brodzisław, Rudolf, Rudolfina, Konrad, Rudolfa',
            2 => 'Gustaw, Karina, Maria, Stefan, Świętosław, Teodota, Edeltruda, Alfreda',
            3 => 'Nikodem, Nikodema, Szczepan, Lidia, Piotr, Dalmacjusz',
            4 => 'Alfred, Mironieg, Perpetua, Maria, Arystarch, Andrzej',
            5 => 'Nonna, Cyriak, Abel, Maria, Memiusz, Oswalda, Oswald, Karolina',
            6 => 'Wincenty, Felicysym, Stefan, Jakub, January, Just, Namir, Nasław, Oktawian',
            7 => 'Licyniusz, Kajetan, Klaudia, Dobiemir, Dorota, Sykstus, Andromeda, Albert, Doryda, Licynia, Konrad, Donata',
            8 => 'Dominik, Niezamysł, Cyriak, Sylwiusz, Cyryl, Emilian, Niegosław',
            9 => 'Klarysa, Miłorad, Domicjan, Domicjana, Dominika, Roland, Roman, Jan, Romuald',
            10 => 'Bernard, Amadea, Wawrzyniec, Wierzchosław, Asteria, Hugona, Bożydar, Wirzchosław, Filomena, Prochor',
            11 => 'Lukrecja, Herman, Włodzimierz, Tyburcja, Zuzanna, Ligia, Aleksander, Klara',
            12 => 'Anicet, Aniceta, Bądzsław, Cyriak, Digna, Eunomia, Euzebiusz, Fotyn, Herkulan, Hilaria, Innocenty, Joanna, Julian, Julianna, Klara, Largus, Lech, Leonida, Makary, Wiktoria',
            13 => 'Radomiła, Hipolit, Sekundyn, Hipolita, Kasjan, Adriana, Helena, Wojbor, Jan, Diana, Radegunda',
            14 => 'Alfred, Euzebiusz, Atanazja, Kalikst, Dobrowoj, Maksymilian, Dobrowoja, Machabeusz, Ursycyn, Majnard',
            15 => 'Napoleon, Maria, Stefan, Arnolf, Arnulf, Trzebiemir, Armida',
            16 => 'Ambroży, Emil, Roch, Domarad, Eleuteria, Stefan, Piotra, Saba, Arsacjusz',
            17 => 'Bertram, Jacek, Miron, Zawisza, Anita, Jaczewoj, Liberat, Eliza, Joanna, Anastazja, Julianna, Angelika, Serwiusz, Żaneta, Klara',
            18 => 'Klara, Ilona, Tacjana, Tworzysława, Helena, Agapit, Bogusława, Bronisław',
            19 => 'Bolesław, Ludwik, Emilia, Sykstus, Juliusz, Jan, Sebald, Julian',
            20 => 'Bernard, Samuel, Sobiesław, Sabin, Sara, Jan, Samuela',
            21 => 'Bernard, Franciszek, Joanna, Wiktoria, Męcimir, Adolf, Filipina, Emilian, Baldwin, Baldwina, Agapiusz',
            22 => 'Fabrycjan, Tymoteusz, Teonas, Fabrycy, Dalegor, Hipolit, Namysław, Maria, Zygfryd, Zygfryda, Cezary, Agatonik, Teona',
            23 => 'Filip, Róża, Walerian, Benicjusz, Sulirad, Zacheusz, Laurenty, Apolinary, Piotra, Klaudiusz, Leoncja, Lubomira',
            24 => 'Michalina, Halina, Anita, Cieszymir, Bartłomiej, Joanna, Jerzy, Malina, Bartosz, Natanael',
            25 => 'Sieciesław, Kalasanty, Ludwik, Luiza, Michał, Elwira, Grzegorz, Arediusz, Gaudencjusz, Teodoryk, Genezjusz',
            26 => 'Wirzchosława, Maria, Maksym, Dobroniega, Joanna, Wiktorian, Konstanty, Ireneusz, Wiktorianna',
            27 => 'Teodor, Józef, Gebhard, Rufus, Monika, Amadea, Małgorzata, Przybymir, Cezary',
            28 => 'Alfons, Hermes, Joachima, Stronisław, Sobiesław, Adelinda, Aleksy, Augustyn',
            29 => 'Mederyka, Sabina, Flora, Racibor, Mederyk, Jan',
            30 => 'Gaudencja, Miron, Tekla, Częstowoj, Adaukt, Rebeka, Piotr',
            31 => 'Rajmund, Bogdan, Albertyna, Amat, Paulina, Teodot'
        ],
        9 => [
            1 => 'Idzi, Bronisław, Bronisława, Sykstus, August, Miłodziad, Melecjusz, Anna',
            2 => 'Absalon, Dziesław, Wilhelm, Stefan, Bogdan, Eliza, Tobiasz, Dionizy, Henryk, Julian, Czesław',
            3 => 'Eufemia, Erazma, Wincenty, Gerarda, Antoni, Bazylisa, Szymona, Mojmir, Bartłomiej, Zenon, Szymon, Dorota, Joachim, Gerard, Izabela, Natalis, Jan, Bronisław, Grzegorz, Przecław',
            4 => 'Rozalia, Liliana, Rościgniew, Daniela, Hermiona, Ida, Ermegarda, Irmegarda, Scypion, Kandyda',
            5 => 'Herakles, Herkulan, Dorota, Fereol, Stronisława, Herkules, Justyna',
            6 => 'Eugenia, Michał, Zachariasz, Magnus, German, Eugeniusz, Zachary, Albin, Aleksja, Uniewit, Gundolf, Ewa, Amoniusz, Petroniusz, Manswet',
            7 => 'Sozont, Melchior, Ryszard, Domasława, Regina, Dobrobąd, Teodoryk, Gratus',
            8 => 'Radosława, Maria, Adrianna, Adrian, Radosław, Nestor',
            9 => 'Gorgoniusz, Aureliusz, Otmar, Piotr, Audomar, Dionizy, Ożanna',
            10 => 'Mścibor, Klemens, Leon, Poliana, Polianna, Pulcheria, Aldona, Mikołaj, Leona, Łukasz, Nimfodora, Kandyda, Piotr, Agapiusz',
            11 => 'Feliks, Jacek, Naczęsław, Dagna, Prot, Jan, Ademar, Piotr',
            12 => 'Gwidon, Maria, Sylwin, Amadeusz, Cyrus, Maja, Sylwina, Teodul',
            13 => 'Eugenia, Filip, Amat, Aureliusz, Morzysław, Aleksander, Litoriusz',
            14 => 'Bernard, Siemomysł, Szymon, Matern, Piotr',
            15 => 'Budzigniew, Maria, Albin, Ekhard, Kamil',
            16 => 'Eugenia, Edyta, Jakub, Kornel, Eufemia, Edda, Sędzisław, Antym, Franciszek, Kamila, Sebastian, Wiktor, Cyprian, Korneli, Kornel',
            17 => 'Ariadna, Szczęsny, Zygmunta, Justyna, Justyn, Narcyz, Hildegarda, Lamberta, Franciszek, Szczęsna, Dezyderiusz, Drogosław, Lambert, Teodora, Piotr, Cherubin, Robert',
            18 => 'Irena, Józef, Fereol, Zachariasz, Dobrowit, Stefania, Zachary, Ryszarda, Tytus, Baltazar, Sobierad',
            19 => 'Więcemir, Teodor, Wilhelmina, Marta, Alfons, Trofim, Konstancja, Festus, January, Zuzanna, Arnolf, Arnulf',
            20 => 'Klemens, Mieczysława, Irena, Faustyna, Oleg, Eustachiusz, Eustachy, Fausta, Dionizy, Miłostryj, Barbara, Perpetua, Agnieszka, Protazy',
            21 => 'Bernardyna, Hipolit, Jonasz, Marek, Laurenty, Mateusz, Ifigenia, Bożeciech, Melecjusz',
            22 => 'Maurycy, Tomasz, Ignacy, Joachim, Prosimir, Józefa',
            23 => 'Bogusław, Liwiusz, Tekla, Boguchwała, Libert, Zachariasz, Zachary, Krzysztof, Elżbieta, Piotr, Selim',
            24 => 'Teodor, Gerard, Maria, Uniegost, Tomir, Gerarda, Twardomir',
            25 => 'Aureli, Aurelia, Aurelian, Herkulan, Wincenty, Rufus, Franciszek, Włodzisław, Eufrozyna, Władysław, Kleofas, Ermenfryda, Irmfryda, Ermenfryd, Irmfryd',
            26 => 'Euzebiusz, Majnard, Cyprian, Kacper, Kasper, Damian, Kosma, Justyna',
            27 => 'Przedbor, Urban, Gaja, Amadeusz, Gajus, Mirela, Adolf, Adolfa, Zybart, Zybert, Zybracht, Zygbert',
            28 => 'Więcesław, Wawrzyniec, Salomon, Wacława, Marek, Sylwin, Wacław, Laurencjusz, Jan, Alodiusz, Sylwina, Tymon, Bernardyn',
            29 => 'Cyriak, Dadzbog, Dadzboga, Lutwin, Dariusz, Franciszek, Fraternus, Gabriel, Gajana, Grimbald, Michalina, Michał, Mikołaj, Rafał, Rypsyma, Teodota, Ludwin',
            30 => 'Euzebia, Felicja, Grzegorz, Zofia, Hieronim, Imisław, Jimisław, Himisław, Wiktor, Honoriusz, Znamir'
        ],
        10 => [
            1 => 'Cieszysław, Benigna, Danuta, Jan, Małobąd, Remigiusz, Igor',
            2 => 'Aleksandra, Leodegar, Stanimir, Teofil, Nasiębor, Ursycyn',
            3 => 'Jan, Teresa, Gerard, Ewalda, Gerarda, Ewald, Kandyd, Eustachy, Sierosław, Częstobrona, Ermegarda, Irmegarda, Romana, Augustyna, Kandyda, Cyprian',
            4 => 'Dobromiła, Dalwin, Franciszek, Konrad, Konrada, Dalewin, Petroniusz',
            5 => 'Justyn, Faust, Galla, Charytyna, Placyd, Konstancjusz, Apolinary, Flawiana, Igor',
            6 => 'Fryderyka, Alberta, Brunon, Roman, Bronisław, Baldwin, Baldwina, Askaniusz, Artur',
            7 => 'Amalia, Tekla, Marek, August, Maria, Rościsława, Stefan, Justyna',
            8 => 'Laurencja, Marcin, Ginter, Ewodia, Guncerz, Gunter, Demetriusz, Pelagia, Symeon, Ewodiusz, Marcjusz, Brygida, Artemon, Gratus',
            9 => 'Przedpełk, Ludwik, Arnold, Guncerz, Ginter, Gunter, Dionizjusz, Bogdan, Atanazja, Bożydar, Sara, Sybilla, Dionizy, Jan, Aaron, Piotr',
            10 => 'Lutomir, Kalistrat, Samuel, Przemysław, Paulin, Franciszek, Tomiła, Tomił, Adalryk, Alderyk, Kasjusz, Eulampiusz, Eulampia',
            11 => 'Burchard, Germanik, Maria, Dobromiła, Aldona, Brunon, Marian, Emil, Emilian, Placyda, Placyd',
            12 => 'Witolda, Wilfryd, Serafin, Cyriak, Edwin, Marcin, Witold, Salwin, Grzymisław, Eustachy, Maksymiliana, Maksymilian',
            13 => 'Daniel, Geraldyna, Wacław, Wacława, Maurycy, Gerald, Teofil, Mikołaj, Edward, Siemisław, Florencjusz, Florenty',
            14 => 'Bernard, Dominik, Alan, Gaja, Kalikst, Fortunata, Gajusz',
            15 => 'Teresa, Sewer, Tekla, Gościsława, Brunon, Jadwiga, Teodoryk',
            16 => 'Aurelia, Radzisław, Ambroży, Gerard, Gaweł, Emil, Gerarda, Florentyna, Grzegorz, Dionizy, Jadwiga',
            17 => 'Małgorzata, Lucyna, Laurentyna, Augustyna, Rudolf, Wiktor, Rudolfina, Seweryna, Sulisława, Ignacy, Marian, Rudolfa, Zuzanna, Heron, Andrzej',
            18 => 'Asklepiades, Bratomił, Julian, Just, Łukasz, Miłobrat, Piotr, Remigia, Remigiusz, Siemowit, Ziemowit',
            19 => 'Jerzy, Paweł, Kleopatra, Ferdynand, Skarbimir',
            20 => 'Budzisława, Irena, Wendelin, Apollo, Witalis, Aurora',
            21 => 'Klementyna, Elżbieta, Hilary, Bernard, Dobromił, Pelagia, Celina, Urszula, Nunilona, Samuel, Wszebora, Piotr',
            22 => 'Filip, Sewer, Kordula, Marek, Kordian, Abercjusz, Alodia',
            23 => 'Seweryn, Giedymin, Małogost, Marlena, Ignacy, Roman, Jan, Domicjusz, Gracjan, Gracjana, Gracjanna, Klotylda',
            24 => 'Filip, Salomon, Marcin, Pamfilia, Boleczest, Marek, Antoni, Walentyna, Rafał',
            25 => 'Daria, Chryzant, Tarazjusz, German, Teodozjusz, Maur, Sambor, Kryspin, Tadea, Cyryn, Cyryna',
            26 => 'Ludomiła, Ewaryst, Lutosław, Lucyna, Leonarda, Amanda',
            27 => 'Frumencjusz, Sabina, Iwona, Wincenty, Siestrzemił, Manfred, Manfreda',
            28 => 'Tadeusz, Wszeciech, Szymon, Juda, Wielimir, Domabor',
            29 => 'Teodor, Narcyz, Longin, Lubgost, Euzebia, Franciszek, Wioleta, Ida, Ermelinda, Piotr',
            30 => 'Zenobia, Przemysław, Gerarda, German, Klaudiusz, Edmund',
            31 => 'Augusta, Alfons, Wolfgang, Antoni, Urban, Godzimir, Lucyla, Saturnin, Narcyz, Lucyliusz, Krzysztof'
        ],
        11 => [
            1 => 'Wszyscy, w tym: Konradyn, Seweryn, Andrzej, Warcisław, Wiktoryna, Konradyna, Nikola, Cyrenia, Julian',
            2 => 'Wiktoryn, Eudoksjusz, Ambroży, Stomir, Małgorzata, Tobiasz, Bogdana, Teodot, Wojsław, Wojsława, Agapiusz',
            3 => 'Sylwia, Huberta, Chwalisław, German, Hubert, Marcin, Bogumił, Cezary',
            4 => 'Karolina, Dżesika, Emeryk, Karol Boromeusz, Olgierd, Modesta, Witalis, Mojżesz, Emeryka, Mściwoj, Mszczujwoj, Perpetua, Joannicjusz',
            5 => 'Florian, Trofima, Marek, Sławomir, Blandyna, Blandyn, Dalemir, Gwidon',
            6 => 'Feliks, Leonard, Trzebowit, Daniela, Teobald, Gabriela',
            7 => 'Achilles, Ernest, Karyna, Amaranta, Melchior, Przemił, Antoni, Florentyn, Engelbert, Gizbert, Żelibrat, Ingarda, Florencjusz, Florenty',
            8 => 'Sędziwoj, Sewerian, Adrian, Sewer, Wiktoryn, Godfryd, Wiktoria, Seweryn, Marcin, Klaudiusz, Wiktor, Hadrian',
            9 => 'Genowefa, Teodor, Bogodar, Teodora, Ursyn, Nestor',
            10 => 'Probus, Nimfa, Stefan, Andrzej, Leon, Leona, Ludomir, Uniebog',
            11 => 'Jozafat, Teodor, Marcin, Spycisław, Bartłomiej, Maciej, Anastazja, Prot',
            12 => 'Jozafat, Marcin, Witold, Jonasz, Renata, Cibor, Czcibor, Renat, Arsacjusz',
            13 => 'Brykcjusz, Walentyn, Eugeniusz, Stanisław, German, Liwia, Augustyna, Mikołaj, Jan, Arkadiusz, Dalmacjusz',
            14 => 'Elżbieta, Wszerad, Józef, Antyd, Serapion, Klementyn, Judyta, Hipacy, Laurenty, Kosma, Lewin, Damian, Agryppa, Teodot, Maria, Paweł, Montan',
            15 => 'Alfons, Idalia, Leopold, Leopoldyna, Roger, Albert, Przybygniew, Artur, Gurias',
            16 => 'Ariel, Otmar, Aureliusz, Audomar, Niedamir, Dionizy, Gertruda, Edmund, Patrokles, Agnieszka',
            17 => 'Jozafat, Hugo, Karolina, Palmira, Zbysław, Floryn, Zacheusz, Grzegorz, Sulibor, Dionizy',
            18 => 'Leonard, Aniela, Otto, Oton, Galezy, Odo, Tomasz, Cieszymysł, Filipina, Karolina, Roman, Gabriela, Józefa, Agnieszka',
            19 => 'Elżbieta, Paweł, Seweryn, Mironiega, Salomea, Kryspin, Małowid, Barbara',
            20 => 'Feliks, Maksencja, Ampeliusz, Hieronim, Sędzimir, Edmund, Anatol, Oktawia, Oktawiusz, Sylwester, Sylwestra, Fortunata, Agapiusz',
            21 => 'Janusz, Twardosław, Maria, Elwira, Albert, Rufus, Regina, Konrad, Wiesław, Heliodor',
            22 => 'Cecylia, Marek, Maur, Wszemiła',
            23 => 'Klemens, Adela, Przedwoj, Erast, Orestes, Felicyta, Fotyna',
            24 => 'Dobrosław, Pęcisław, Gerard, Emilia, Flora, Franciszek, Protazy, Jan, Biruta, Jaśmina, Felicjana, Felicjanna, Agnieszka, Joachim, Twardomir',
            25 => 'Erazm, Katarzyna, Tęgomir, Piotr',
            26 => 'Leonard, Sylwester, Dobiemiest, Delfin, Lechosława, Lechosław, Jan, Konrad, Sylwestra, Piotr',
            27 => 'Wirgiliusz, Jozafat, Zygfryd, Stojgniew, Gustaw, Dominik, Damazy, Zygfryda, Oda, Walery, Maksymilian, Sekundyn, Achacjusz, Achacy, Bernardyn',
            28 => 'Grzegorz, Lesław, Zdzisław, Gościrad, Lesława, Jakub, Rufin, Ginter, Guncerz, Gunter, Kwieta, Berta',
            29 => 'Klementyna, Walter, Błażej, Bolemysł, Przemysł, Fryderyk, Saturnin, Paramon',
            30 => 'Zbysława, Andrzej, Justyna, Konstancjusz, Maura, Tadea, Kutbert'
        ],
        12 => [
            1 => 'Eligia, Natalia, Platon, Edmund, Eligiusz, Blanka, Sobiesława, Gosława',
            2 => 'Bibiana, Bibianna, Aurelia, Wiktoryn, Zbylut, Ludwina, Balbina, Sulisław, Paulina, Sylweriusz, Budzisława, Budzisław',
            3 => 'Uniemir, Kasjan, Lucjusz, Franciszek, Kryspin, Ksawery, Atalia, Gerlinda, Biryn, Sofoniasz',
            4 => 'Klemens, Chrystian, Barbara, Krystian, Hieronim, Melecjusz',
            5 => 'Anastazy, Kryspina, Sabina, Kryspin, Gerald, Pęcisława, Krystyna, Sabbas, Dalmacjusz',
            6 => 'Nikola, Angelika, Heliodor, Agata, Dionizja, Mikołaj, Emilian, Leoncja, Piotr, Honorata',
            7 => 'Ambroży, Marcin, Ninomysł, Agaton, Marcisław, Józefa, Polikarp, Zdziemił, Sabin',
            8 => 'Maria, Narcyza, Apollo, Boguwola',
            9 => 'Leokadia, Waleria, Joachim, Delfina, Wiesław, Wielisława, Wiesława, Piotr',
            10 => 'Polidor, Brajan, Daniel, Judyta, Maria, Andrzej, Julia, Switun, Unierad, Unirad',
            11 => 'Stefan, Damazy, Waldemar, Wojmir, Wilburga',
            12 => 'Adelajda, Dagmara, Edburga, Suliwuj, Paramon, Spirydon, Aleksander, Ada, Przybysława, Maksencjusz',
            13 => 'Bernarda, Otylia, Edburga, Jodok, Róża, Włodzisława, Auksencja, Łucja, Auksencjusz, Auksenty, Aubert',
            14 => 'Pompejusz, Sławobor, Alfred, Nahum, Arseniusz, Noemi, Izydor, Heron',
            15 => 'Cecylia, Walerian, Mścigniew, Wolimir, Drogosława',
            16 => 'Alina, Adelajda, Zdzisława, Ananiasz, Albina, Dyter, Deder, Tyter',
            17 => 'Florian, Łazarz, Łukasz, Olimpia',
            18 => 'Bogusław, Wszemir, Arkadia, Wilibald, Auksencja, Winebald, Winibalda, Wunibald, Auksencjusz, Auksenty',
            19 => 'Tymoteusz, Nemezjusz, Abraham, Dariusz, Beniamin, Urban, Mścigniew, Bogumiła',
            20 => 'Bogumiła, Dominik, Amon, Liberat, Dagmara, Teofil, Ursycyn',
            21 => 'Tomisław, Balbin, Tomasz, Honorat, Festus, Piotr',
            22 => 'Drogomir, Ksawera, Honorata, Zenon, Franciszka, Gryzelda, Flawian, Beata, Ischyrion',
            23 => 'Wiktoria, Anatola, Sławomir, Sławomira, Dagobert, Anatolia, Teodul',
            24 => 'Adela, Grzymisława, Druzjanna, Ewa, Godzisława, Irmina, Druzjan, Adamina, Grzegorz, Ewelina, Hermina, Zenobiusz, Tarsylla, Adam',
            25 => 'Eugenia, Mateusz, Piotr, Siemisław, Domna',
            26 => 'Wrociwoj, Szczepan, Dionizy',
            27 => 'Żaneta, Fabia, Fabiola, Jan, Cezary, Krystyna',
            28 => 'Teofila, Antoni, Ema, Teonas, Dobrowieść, Teona, Godzisław',
            29 => 'Trofim, Jonatan, Gerarda, Dominik, Marcin, Tomasz, Gosław, Dawid, Gerard, Jakert, Tadea',
            30 => 'Sewer, Anizja, Egwin, Eugeniusz, Rajner, Dionizy, Uniedrog, Irmina',
            31 => 'Sylwester, Donata, Mariusz, Melania, Katarzyna, Saturnina, Sebastian, Tworzysław, Sylwestra'
        ],
    ];

    public function load(ObjectManager $manager): void
    {
        foreach (self::DAY_NAMES as $month => $days) {
            foreach ($days as $day => $names) {
                $dayName = new NameDay();
                $dayName->setMonth($month);
                $dayName->setDay($day);
                $dayName->setNames($names);
                $manager->persist($dayName);
            }
        }

        $manager->flush();
    }
}
